Adding basic test-cases for #391
epam/NGB pull request #402
Opened 2021-05-17 08:46 UTC by Tatyana2022

This PR introduces test cases for #391  issue implementation and minor cosmetic fixes for the case with simple conditions

2021-05-17 10:08 UTC, Tatyana2022 commented
@NShaforostov @mzueva @sidoruka  I apologize, I forgot to write right away. Could you view the test cases, please?

2021-05-19 10:22 UTC, NShaforostov requested changes
Perform minor fixes according to comments, please.

And update the Pull request description according to all introduced cases.

2021-05-19 10:22 UTC, NShaforostov commented on docs/test-cases/vcf-highlight/Conditions/Changing_profile_in_the_settings.md
> +| 11| Look at variation on vcf track in Browser| Variation is highlighted in color  **'ff0000'(red)** along all its length in expanded and collapsed view
Add separate steps for switching between VCF-track view ("expanded" and "collapsed")

2021-05-19 10:22 UTC, NShaforostov commented on docs/test-cases/vcf-highlight/Conditions/Changing_profile_in_the_settings.md
> +| 14| Find Variation on Position **chr X:12587867**| Background of variation is highlighted  in **"fff000"(yellow)** along all its length in expanded and collapsed view on **Variants panel** and **vc
Add separate steps for switching between VCF-track view ("expanded" and "collapsed")

2021-05-19 10:22 UTC, NShaforostov commented on docs/test-cases/vcf-highlight/Conditions/Changing_profile_in_the_settings.md
> +| 13| Find Variation from previous profile on Position **chr X:12584271**| Conditions are changed. Background of variation **isn't highlighted** in 'ff0000' (red) color **on Variants panel** and **vc
> Find Variation from previous profile

Remove "from previous profile"

2021-05-19 10:22 UTC, NShaforostov commented on docs/test-cases/vcf-highlight/Conditions/Highlight_vcf_with_complex_conditions.md
> +| 11| Look at variation on vcf track in Browser| Variation is highlighted in color  **'0083ff'(blue)** along all its length in expanded and collapsed view
Add separate steps for switching between VCF-track view ("expanded" and "collapsed")

2021-05-19 10:22 UTC, NShaforostov commented on docs/test-cases/vcf-highlight/Conditions/Highlighting_the_same_variation_with_different_conditions.md
> +| 11| Look at variation on vcf track in Browser| <li> Variation is highlighted in color  **'ff0000'(red)** along all its length in expanded and collapsed view <li> Variation **isn't** highlighted in
Add separate steps for switching between VCF-track view ("expanded" and "collapsed")

2021-05-19 10:22 UTC, NShaforostov commented on docs/test-cases/vcf-highlight/Conditions/Structural_variations_(BND).md
> +| 7 | Select datasets and vcf files from **Prerequisites** | Vcf files is selected in datasets |
> Vcf files is selected

Fix to "Vcf files are selected"

2021-05-19 10:22 UTC, NShaforostov commented on docs/test-cases/vcf-highlight/Conditions/Structural_variations_(BND).md
> +| 11| Look at variation on vcf track in Browser| Variation and it's label is highlighted in color  **'ff0000'(red)** along all its length in expanded and collapsed view
Add separate steps for switching between VCF-track view ("expanded" and "collapsed")

2021-05-19 10:22 UTC, NShaforostov commented on docs/test-cases/vcf-highlight/GUI/Bubble.md
> +| 11| Select 'Collapsed' view
Change to something like "At the vcf-track, select 'Collapsed' view (if it was not set previously)"

2021-05-19 15:19 UTC, mzueva approved these changes

2021-05-31 14:27 UTC, merged