Issue 395 blast search backend implementation canceled status
epam/NGB pull request #440
Opened 2021-06-11 09:35 UTC by okolesn

# Description
Cancel task improvement for 
[[BLAST Search] Backend implementation](https://github.com/epam/NGB/issues/395).

Task status will be updated even If task wasn't cancelled. Task status is taken from error message.

2021-06-22 13:31 UTC, SilinPavel requested changes

2021-06-22 13:31 UTC, SilinPavel commented on server/catgenome/src/main/java/com/epam/catgenome/entity/blast/BlastTaskStatus.java
>      private long id;
could we make it `int` and don't cast it for `idMap`

2021-06-22 13:31 UTC, SilinPavel commented on server/catgenome/src/main/java/com/epam/catgenome/entity/blast/BlastTaskStatus.java
>      private long id;
also could be final

2021-06-22 13:31 UTC, SilinPavel commented on server/catgenome/src/main/java/com/epam/catgenome/entity/blast/BlastTaskStatus.java
>      private boolean finalStatus;
should be final

2021-06-22 13:31 UTC, SilinPavel commented on server/catgenome/src/main/java/com/epam/catgenome/entity/blast/BlastTaskStatus.java
> +    private static Map<Long, BlastTaskStatus> idMap = new HashMap<>((int) CREATED.getId());
could be final

2021-06-22 13:40 UTC, SilinPavel commented on server/catgenome/src/main/java/com/epam/catgenome/manager/blast/BlastRequestManager.java
>              Result<BlastRequestInfo> result = QueryUtils.execute(blastApi.cancelTask(id));
could be joined

2021-06-25 09:28 UTC, merged

2021-08-19 11:41 UTC, Tatyana2022 commented
***Verified***